apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/storage/n8n
    server: 10.0.0.60
  persistentVolumeReclaimPolicy: Retain
