apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: n8n-pv                                      # <-- keep it
  storageClassName: ""                                    # <-- keep it
  #volumeMode: Filesystem

