apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-ee488ef9-bfe8-4ce4-b9ca-1d637bee0127   # <-- keep it
  storageClassName: local-path                            # <-- keep it
  volumeMode: Filesystem

